### ISSUE TITLE
Wallet account view

### ISSUE THREAD

**Issue by fairfaxache** [xelis-project/xelis-docs#3]
Where are stored my coins?
Your balance is stored on chain, not on your computer or in your wallet.
The wallet allows you to manage these funds as long as you have access to it.

Always keep your seed or a backup of your wallet file. This ensures you can access your funds if your device is lost or unusable.

With reference to the above statement, i  have been mining for a week and have under 1 Xel but id like to see it in the wallet not as 3 transactions that i cannot read because of encryption. How do i do this I cannot find an explanation and my Discord is playing up

**Comment by Slixe** [comment]
How have you generated an address ? Just use the wallet, connect it to a daemon synced, and wait the balance to be synced.

Balances are private and only visible by owner with the seed/private key associated.

**Comment by fairfaxache** [comment]
> How have you generated an address ? Just use the wallet, connect it to a daemon synced, and wait the balance to be synced.
> 
> Balances are private and only visible by owner with the seed/private key associated.

I just checked again and funds have turned up. Sorry to waste your time
Thanks

**Comment by Slixe** [comment]
No worries, here to help :)

Wallet may have a bug sometimes when you open it, it doesn’t scan the last balance directly. Thats fixed for incoming release :)

Closing!

**Comment by fairfaxache** [comment]
All sorted thanks for your help Sent using the GMX mail appOn 25/06/2024 at 20:07, Slixe wrote:
                
            
            
                
                    From: "Slixe" ***@***.***>Date: 25 June 2024To: "xelis-project/xelis-docs" ***@***.***>Cc: "Author" ***@***.***>,"fairfaxache" ***@***.***>Subject: Re: [xelis-project/xelis-docs] Wallet account view (Issue #3)
                
                
How have you generated an address ? Just use the wallet, connect it to a daemon synced, and wait the balance to be synced.
Balances are private and only visible by owner with the seed/private key associated.
